insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (1, 'Zontrax', 'XG-930-A', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (2, 'Regrant', 'RV-671-F', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (3, 'Treeflex', 'QW-803-L', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (4, 'Span', 'JD-703-E', 3);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (5, 'Vagram', 'HQ-020-H', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (6, 'Asoka', 'SC-769-N', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (7, 'Otcom', 'TQ-843-V', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (8, 'Alpha', 'EO-689-F', 3);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (9, 'Kanlam', 'WG-211-Z', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (10, 'Y-Solowarm', 'MA-328-C', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (11, 'Fix San', 'WU-541-A', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (12, 'Alphazap', 'DV-976-B', 6);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (13, 'Hatity', 'US-117-X', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (14, 'Alphazap', 'GK-881-R', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (15, 'Sonsing', 'HP-791-W', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (16, 'Gembucket', 'PO-210-Z', 5);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (17, 'Andalax', 'XR-911-N', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (18, 'Wrapsafe', 'NL-211-S', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (19, 'Ventosanzap', 'MY-418-N', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (20, 'Mat Lam Tam', 'TS-450-J', 11);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (21, 'Viva', 'QH-058-R', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (22, 'Stronghold', 'AH-841-A', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (23, 'Tres-Zap', 'PG-124-T', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (24, 'Alpha', 'ZH-405-X', 12);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (25, 'Flexidy', 'PC-514-R', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (26, 'Konklux', 'IR-732-J', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (27, 'Konklab', 'OM-937-A', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (28, 'Ronstring', 'MZ-578-I', 19);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (29, 'Stim', 'KN-920-R', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (30, 'Wrapsafe', 'FS-593-U', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (31, 'Fix San', 'OM-386-R', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (32, 'Hatity', 'RY-895-P', 4);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (33, 'Tres-Zap', 'PM-188-Y', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (34, 'Sonair', 'AY-856-F', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (35, 'Home Ing', 'PV-478-C', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (36, 'Latlux', 'YH-204-P', 11);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (37, 'Fix San', 'IR-736-D', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (38, 'Solarbreeze', 'ZO-499-D', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (39, 'Tampflex', 'XG-230-K', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (40, 'Bytecard', 'CH-888-R', 3);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (41, 'Namfix', 'PB-713-R', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (42, 'Voltsillam', 'BK-483-O', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (43, 'Wrapsafe', 'TK-653-K', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (44, 'Opela', 'FE-710-B', 24);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (45, 'Biodex', 'BW-792-F', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (46, 'Zoolab', 'EV-051-G', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (47, 'Andalax', 'NM-728-Y', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (48, 'Zaam-Dox', 'MA-213-O', 1);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (49, 'Otcom', 'LI-703-I', null);
insert into AGENCIA (agencia_id, nombre, clave, agencia_anexa_id) values (50, 'Matsoft', 'PV-964-N', null);
